trigger: none

pool:
 name: cicdpool

steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'cicdinfra_sc'
    backendAzureRmStorageAccountName: 'terraformstatefile55'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev.terraform.state'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'cicdinfra_sc'







