trigger: none

pool:
 name: cicdpool

stages:
  # - stage: initandplan
  #   displayName: init and plan
  #   jobs:
  #     - job: terraforminitplan
  #       steps:
  #       - task: TerraformTask@5
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'init'
  #           backendServiceArm: 'cicdinfra_sc'
  #           backendAzureRmStorageAccountName: 'terraformstatefile55'
  #           backendAzureRmContainerName: 'tfstate'
  #           backendAzureRmKey: 'dev.terraform.state'

  #       - task: TerraformTask@5
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'plan'
  #           environmentServiceNameAzureRM: 'cicdinfra_sc'

  # - stage: manualvalidation
  #   displayName: manual validation
  #   dependsOn: initandplan
  #   jobs:
  #     - job: approval
  #       pool: server
  #       steps: 
  #       - task: ManualValidation@1
  #         inputs:
  #           notifyUsers: 'manoj@nevalosstechnologies.com'
  #           approvers: 'manoj@nevalosstechnologies.com'
        


  - stage: apply
    displayName: terraform apply
    jobs: 
      - job: terraformapply
        steps:  
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'cicdinfra_sc'
              backendAzureRmStorageAccountName: 'terraformstatefile55'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev.terraform.state'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: 'cicdinfra_sc'







